drop table if exists item CASCADE;
create table item
(
    id        bigint generated by default as identity,
    item_name varchar(10),
    price     integer,
    quantity  integer,
    primary key (id)
);

insert into item(item_name, price, quantity) values ('ItemTest1', 10000, 10);
insert into item(item_name, price, quantity) values ('ItemTest2', 10000, 10);
insert into item(item_name, price, quantity) values ('ItemTest3', 10000, 10);