
/**
  초기 설정
 */
drop table if exists member CASCADE;
create table member
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

/**
  값 집어넣기
 */
insert into member(name)
values ('sping3');